[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "GITHUB_OWNER, GITHUB_REPO, CONTENT_ROOT, GITHUB_BRANCH"
  SECRETS_SCAN_OMIT_PATHS = ".env.example"
